### ISSUE TITLE
Raspberry Pi on Wi-Fi

### ISSUE THREAD

**Issue by zgrzezly** [RobertWojtowicz/export2garmin#42]
Hi,
It seems to me that there is an issue with the program's operation when the Raspberry Pi is running on Wi-Fi. Running import_data.sh as a process causes Wi-Fi problems. The Raspberry Pi continuously disconnects and reconnects to Wi-Fi. The error on the router is "DC:A6:32:66:12:88@wlan1: disconnected, extensive data loss, signal strength -66". Naturally, the data does not import into Garmin Connect. It works fine with a wired connection.
BR Zbigniew

**Comment by RobertWojtowicz** [comment]
Hi, @zgrzezly 

It sounds like a problem on the side of the raspberry pi, specifically the drivers of wifi and bt support...

BR,
T
Robert

**Comment by zgrzezly** [comment]
I am sending both data from miscale and omron, Rpi4 with bookworm on board without GUI

**Comment by RobertWojtowicz** [comment]
Hi, @zgrzezly

I recreated the same environment at my home (RPI 4B 4GB). The problem with you probably lies in poor WiFi coverage or the band you are operating on and frequency (2.4GHz instead of 5GHz ?, BT works on 2.4GHz).

In my case the problem does not occur, the only thing I can complain about is the range of the built-in BT is very small (what I wrote in the manual), in my WiFi is UniFi LR-6 (WiFi 6 Long Range).

BR,
Robert

**Comment by zgrzezly** [comment]
I confirm that the issue was with sharing the 2.4GHz band between Wi-Fi and Bluetooth. After switching Wi-Fi to 5GHz, it works correctly. The limited range of the built-in Bluetooth is another matter, I am waiting for an external Bluetooth module to extend it.
BR,
zgrzezly
